
theme: minima

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - module_1_WBP1.md
  - module_linux_scripting.md
  - module_3_WBP2.md

header_pages:
- about.md
- portfolio.md