
theme: minima
#remote_theme: jekyll/minima


# theme: minima
# jekyll-theme-minimal

#remote_theme: chrisrhymes/bulma-clean-theme
# remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#- jekyll-remote-theme
#- jekyll-feed

include:
- module_1_WBP1.md
- module_linux_scripting.md
- module_3_WBP2.md